### ISSUE TITLE
search results 1 - top 3 resources

### ISSUE THREAD

**Issue by garussell** [westonio/next-steps-front-end#16]
As a visitor, when I visit the home page, 
I see a section called "I need urgent help now!" 
When I enter my location, select one or more categories from the section and click on the "Get Help!" button,
Then, I am taken to the search results page where I see a section for each checkbox I selected
Within each section, I see the top 3 search results
Each resource shows the Provider's name, address, city, and description

**Comment by westonio** [comment]
Top 3 resources for each category instead?

**Comment by westonio** [comment]
I need urgent help section - Endpoints:

GET /api/v0/health_care (medical care)
GET /api/v0/shelters (shelter for tonight)
GET /api/v0/basic_needs (food and other)
GET /api/v0/crisis_hotline (crisis hotline)
I would like assistance with section - Endpoints:

GET /api/v0/benefits (medicaid / non-cash benefits)
GET /api/v0/mental_health_care
GET /api/v0/housing
GET /api/v0/food_banks
GET /api/v0/addiction_management

**Comment by westonio** [comment]
UPDATE:
- GET /search?Keyword="checkbox"&location="location_entry"

**Comment by garussell** [comment]
Thank you for the update!
