### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by garussell** [westonio/next-steps-front-end#23]
On the User Login page, I see a section that says "Do you need to create an account?  Click Here to create a user account to save your favorite providers and track your Next Steps progress."  If I click that link I'm redirected to the registration page

**Comment by garussell** [comment]
Registration page:

- Route: get '/login', to: 'registrations#login_form'
              post '/login', to: 'registrations#login'
              delete '/logout', to: 'registrations#logout'
- Controller: RegistrationsController
- Action(s): login_form (post), login (get), logout (delete)

**Comment by kcockett** [comment]
Updates to registration routes for users.  As per our previous lesson on authentication (https://backend.turing.edu/module3/lessons/intro_to_basic_auth) I am using the following non-RESTful routes:

get "/users/login", to: "users#login_form"
post "users/login", to: "users#login"
