### ISSUE TITLE
Login Page 2

### ISSUE THREAD

**Issue by garussell** [westonio/next-steps-front-end#7]
I see a section to login to my account that says "Enter your username", and "enter your password", and a button to submit (link back)

**Comment by garussell** [comment]
Starting from get '/login'

Submit button is post '/login'

**Comment by kcockett** [comment]
Updates to registration routes for users. As per our previous lesson on authentication (https://backend.turing.edu/module3/lessons/intro_to_basic_auth) I am using the following non-RESTful routes:

get "/users/login", to: "users#login_form"
post "users/login", to: "users#login"
