### ISSUE TITLE
welcome page  3 - get help check boxes

### ISSUE THREAD

**Issue by garussell** [westonio/next-steps-front-end#8]
On the welcome page, when I select options by checking boxes, and then I click_on "Get Help!", I am directed to the search results page

**Comment by garussell** [comment]
Search Results Page:
- Route: search_results_path
- Controller: SearchController
- Action: results (index)

Functionality:
Clicking boxes adds elements to the array and each are individual query that we iterate through to access API data.

**Comment by westonio** [comment]
Closing as completed in part of the last PR
